# Generated by Django 2.0.1 on 2018-02-01 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelTable(
            name='student',
            table='student_info',
        ),
    ]
