# Generated by Django 2.0.1 on 2018-02-01 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0002_auto_20180201_1401'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table=None,
        ),
    ]
